//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngelMacro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AngelMacro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE COLOR THRESHOLD.
        /// </summary>
        public static string add_color_threshold_change {
            get {
                return ResourceManager.GetString("add_color_threshold_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITION.
        /// </summary>
        public static string add_condition {
            get {
                return ResourceManager.GetString("add_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP SCRIPT.
        /// </summary>
        public static string add_end {
            get {
                return ResourceManager.GetString("add_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEAT UNTIL.
        /// </summary>
        public static string add_until {
            get {
                return ResourceManager.GetString("add_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONAL LOOP.
        /// </summary>
        public static string add_while {
            get {
                return ResourceManager.GetString("add_while", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on start.
        /// </summary>
        public static string auto_minimize {
            get {
                return ResourceManager.GetString("auto_minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro is invalid.
        /// </summary>
        public static string command_error_text {
            get {
                return ResourceManager.GetString("command_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command error.
        /// </summary>
        public static string command_error_title {
            get {
                return ResourceManager.GetString("command_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No start delay.
        /// </summary>
        public static string fast_start {
            get {
                return ResourceManager.GetString("fast_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert code.
        /// </summary>
        public static string insert_code {
            get {
                return ResourceManager.GetString("insert_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main color threshold.
        /// </summary>
        public static string main_color_threshold {
            get {
                return ResourceManager.GetString("main_color_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string mouse {
            get {
                return ResourceManager.GetString("mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open saved macro file.
        /// </summary>
        public static string open_macro {
            get {
                return ResourceManager.GetString("open_macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause recording (F6).
        /// </summary>
        public static string pause_recording {
            get {
                return ResourceManager.GetString("pause_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record delays.
        /// </summary>
        public static string record_delays {
            get {
                return ResourceManager.GetString("record_delays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cursor Location.
        /// </summary>
        public static string record_mouse_location {
            get {
                return ResourceManager.GetString("record_mouse_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record scroll wheel.
        /// </summary>
        public static string record_scroll_wheel {
            get {
                return ResourceManager.GetString("record_scroll_wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string replay {
            get {
                return ResourceManager.GetString("replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run macro (F7).
        /// </summary>
        public static string run_macro {
            get {
                return ResourceManager.GetString("run_macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save macro file.
        /// </summary>
        public static string save_macro {
            get {
                return ResourceManager.GetString("save_macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script unlocked! Be careful when editing it..
        /// </summary>
        public static string script_unlocked {
            get {
                return ResourceManager.GetString("script_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        public static string start_recording {
            get {
                return ResourceManager.GetString("start_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop macro (F8).
        /// </summary>
        public static string stop_macro {
            get {
                return ResourceManager.GetString("stop_macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle topmost.
        /// </summary>
        public static string toggle_topmost {
            get {
                return ResourceManager.GetString("toggle_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock script.
        /// </summary>
        public static string unlock_script {
            get {
                return ResourceManager.GetString("unlock_script", resourceCulture);
            }
        }
    }
}
